workspace 'Resourced.xcworkspace'
project 'Resourced.xcodeproj'
platform :ios, '11.0'

target 'Resourced' do
  use_frameworks!
  pod 'ResourcedPod', :git => 'https://github.com/tom-xy/PodspecExample.git'
end
