source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

workspace 'Library.xcworkspace'
project 'Library.xcodeproj'
platform :ios, '11.0'

target 'Library' do
  use_frameworks!
  pod 'LibraryPod', :git => 'https://github.com/tom-xy/PodspecExample.git'
end
