source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

workspace 'Embedded.xcworkspace'
project 'Embedded.xcodeproj'
platform :ios, '11.0'

target 'Embedded' do
  use_frameworks!
  # Default
  # pod 'EmbeddedPod', :git => 'https://github.com/tom-xy/PodspecExample.git'

  # Specify sub-pods
  # pod 'EmbeddedPod', :subspecs => [ 'Animal', 'Plant'], :git => 'https://github.com/tom-xy/PodspecExample.git'
  
  pod 'EmbeddedPod/Animal', :git => 'https://github.com/tom-xy/PodspecExample.git'
end
